/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JASON' at '7/21/16 10:52 PM' with Gradle 2.14
 *
 * @author JASON, @date 7/21/16 10:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
